//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWSEditor.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BodySamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BodySamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWSEditor.Common.BodySamples", typeof(BodySamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Test document&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///This is a html body.
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt;.
        /// </summary>
        internal static string BasicHtmlBody {
            get {
                return ResourceManager.GetString("BasicHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///
        ///&lt;title&gt;Test document&lt;/title&gt;
        ///               &lt;meta name=&quot;keywords&quot; content=&quot;test, html, form, sample, example&quot; /&gt;
        ///
        ///&lt;script&gt;
        ///function test()
        ///{
        ///               
        ///
        ///}
        ///&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///&lt;!-- This is a comment, so you should not see it rendered. --&gt;
        ///
        ///&lt;hr&gt;
        ///The following is some basic text markup: &lt;br/&gt;
        ///This is plain text. &lt;br/&gt;
        ///&lt;b&gt;This is bold text. &lt;/b&gt; &lt;br/&gt;
        ///&lt;i&gt;This is italic text. &lt;/i&gt;&lt;br/&gt;
        ///&lt;p&gt;This is a paragraph. &lt;/p&gt;&lt;br/&gt;
        ///&lt;p&gt;This is &lt;sup&gt; superscript. &lt;/sup&gt;&lt;/p&gt;&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ManyFormatsHtmlBody {
            get {
                return ResourceManager.GetString("ManyFormatsHtmlBody", resourceCulture);
            }
        }
    }
}
