//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWSEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWSEditor.Resources.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create EWSEditor log file at {0}.  Logging will be disabled for this session..
        /// </summary>
        internal static string FailCreateLogFileException {
            get {
                return ResourceManager.GetString("FailCreateLogFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download the Exchange Web Services Managed API.
        /// </summary>
        internal static string MSG_EWS_API_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("MSG_EWS_API_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonation configuration is invalid..
        /// </summary>
        internal static string MSG_IMPERSON_REQ {
            get {
                return ResourceManager.GetString("MSG_IMPERSON_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no attachments on this item to display..
        /// </summary>
        internal static string MSG_NO_ATTACHMENTS {
            get {
                return ResourceManager.GetString("MSG_NO_ATTACHMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWSEditor cannot start because it could not find the Exchange Web Service Managed API (Microsoft.Exchange.WebServices.DLL) installed on this machine..
        /// </summary>
        internal static string MSG_NO_EWS_API {
            get {
                return ResourceManager.GetString("MSG_NO_EWS_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must configure a service URL either using Autodiscover or explicitly specifying one..
        /// </summary>
        internal static string MSG_SERVICE_REQ {
            get {
                return ResourceManager.GetString("MSG_SERVICE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use specific credentials you must input at least a user name and password..
        /// </summary>
        internal static string MSG_SPECIFY_CREDS {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_CREDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated items in {0}.
        /// </summary>
        internal static string TITLE_CONTENTS_ASSOC {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_ASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in {0}.
        /// </summary>
        internal static string TITLE_CONTENTS_FOLDER {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft deleted tems in {0}.
        /// </summary>
        internal static string TITLE_CONTENTS_SOFT {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_SOFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string TITLE_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("TITLE_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications from {0}.
        /// </summary>
        internal static string TITLE_NOTIFICATIONS_FOLDER {
            get {
                return ResourceManager.GetString("TITLE_NOTIFICATIONS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More appointments were returned in the search but only the first {0} will be displayed..
        /// </summary>
        internal static string WARN_CALENDARVIEW_LIMT {
            get {
                return ResourceManager.GetString("WARN_CALENDARVIEW_LIMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log message not found..
        /// </summary>
        internal static string WARN_EWS_LOG_MESSAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("WARN_EWS_LOG_MESSAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EWSEditor does not currently display more than 1000 items in the contents view.  This folder has more items in it, only the first 1000 are displayed..
        /// </summary>
        internal static string WARN_ITEM_VIEW_COUNT_LIMIT {
            get {
                return ResourceManager.GetString("WARN_ITEM_VIEW_COUNT_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no binding selected..
        /// </summary>
        internal static string WARN_NO_BINDING {
            get {
                return ResourceManager.GetString("WARN_NO_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no folder selected..
        /// </summary>
        internal static string WARN_NO_FOLDER {
            get {
                return ResourceManager.GetString("WARN_NO_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select individual schema properties, not a schema name..
        /// </summary>
        internal static string WARN_SELECT_SCHEMA_PROPS {
            get {
                return ResourceManager.GetString("WARN_SELECT_SCHEMA_PROPS", resourceCulture);
            }
        }
    }
}
